import { Leaf } from 'lucide-react'
import { useState } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { isSupabaseConfigured, supabase } from '../lib/supabase'

export default function AuthPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [mode, setMode] = useState('sign-in'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to="/inventory" replace />
  const submit = async (event) => { event.preventDefault(); setMessage(''); setBusy(true); const action = mode === 'sign-in' ? supabase.auth.signInWithPassword({ email, password }) : supabase.auth.signUp({ email, password }); const { data, error } = await action; setBusy(false); if (error) return setMessage(error.message); if (data.session) navigate(location.state?.from?.pathname || '/inventory', { replace: true }); else setMessage('Check your email to confirm your account, then sign in.') }
  return <main className="auth-page"><section className="auth-panel"><div className="brand brand--auth"><span className="brand__mark"><Leaf size={19} /></span><span>ShelfSense <b>AI</b></span></div><p className="eyebrow">Your food, understood</p><h1>{mode === 'sign-in' ? 'Welcome back.' : 'Start wasting less.'}</h1><p>Sign in to access your private food inventory. Your data is protected by Supabase row-level security.</p>{!isSupabaseConfigured ? <div className="notice notice--warning">Supabase is not configured. Add the variables from <code>.env.example</code> to <code>.env.local</code>, then restart the app.</div> : <form onSubmit={submit} className="auth-form"><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} /></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" minLength="6" required autoComplete={mode === 'sign-in' ? 'current-password' : 'new-password'} value={password} onChange={(e) => setPassword(e.target.value)} /></div>{message && <div className="notice">{message}</div>}<button className="button button--wide" disabled={busy}>{busy ? 'Please wait…' : mode === 'sign-in' ? 'Sign in' : 'Create account'}</button></form>} {isSupabaseConfigured && <button className="text-button" onClick={() => { setMode(mode === 'sign-in' ? 'sign-up' : 'sign-in'); setMessage('') }}>{mode === 'sign-in' ? 'New to ShelfSense? Create an account' : 'Already have an account? Sign in'}</button>}</section></main>
}
