import { ArrowLeft, CalendarDays, Edit3, MapPin, Package, ShoppingBasket, Sparkles, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import InventoryForm from '../components/InventoryForm'
import LoadingState from '../components/LoadingState'
import Modal from '../components/Modal'
import StateMessage from '../components/StateMessage'
import StatusBadge from '../components/StatusBadge'
import { deleteInventoryItem, fetchInventoryItem, recordConsumption, recordWaste, updateInventoryItem } from '../services/inventory'
import { calculateEstimatedExpiry, daysUntil, formatDate, formatMoney, formatStorage, getFreshnessStatus } from '../utils/inventory'
import { fetchPredictionForItem } from '../services/predictions'
import RiskBadge from '../components/RiskBadge'
import { riskLabel } from '../utils/prediction'
import { fetchRecipesForInventoryItem, generateRescueRecipes } from '../services/recipes'
import RecipeCard from '../components/RecipeCard'
import AIGenerationState from '../components/AIGenerationState'

export default function InventoryDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const [item, setItem] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [modal, setModal] = useState(null)
  const [prediction, setPrediction] = useState(null)
  const [recipes, setRecipes] = useState([]); const [aiLoading, setAiLoading] = useState(false); const [aiError, setAiError] = useState(''); const autoRequested = useRef(false)
  const load = useCallback(async (forcePrediction = false) => { setLoading(true); setError(false); const { data, error: loadError } = await fetchInventoryItem(id); if (loadError) { console.error('Inventory detail load failed', loadError); setError(true) } else { setItem(data); const [predictionResult, recipeResult] = await Promise.all([fetchPredictionForItem(data, forcePrediction), fetchRecipesForInventoryItem(id)]); if (predictionResult.error) console.error('Prediction load failed', predictionResult.error); else setPrediction(predictionResult.data); if (!recipeResult.error) setRecipes(recipeResult.data || []) } setLoading(false) }, [id])
  useEffect(() => { load() }, [load])
  const generate = useCallback(async () => { setAiLoading(true); setAiError(''); const result = await generateRescueRecipes(id); setAiLoading(false); if (result.error) { console.error('AI rescue generation failed', result.error); setAiError(result.error.message); return } setRecipes(result.data.recipes || []) }, [id])
  useEffect(() => { if (searchParams.get('rescue') === '1' && item && prediction && !autoRequested.current) { autoRequested.current = true; generate() } }, [generate, item, prediction, searchParams])
  if (loading) return <section className="page"><LoadingState rows={3} /></section>
  if (error || !item) return <section className="page"><StateMessage icon={Package} variant="error" title="Inventory item unavailable" message="It may have been removed, or we couldn’t load it." /></section>
  const expiry = calculateEstimatedExpiry(item); const days = daysUntil(expiry); const status = getFreshnessStatus(item)
  const completeAction = async (type, values) => { const fn = type === 'consume' ? recordConsumption(item.id, values.quantity, values.notes) : recordWaste(item.id, values.quantity, values.reason, values.notes); const { error: actionError } = await fn; if (actionError) throw actionError; setModal(null); await load(true) }
  return <section className="page detail-page"><Link className="back-link" to="/inventory"><ArrowLeft size={16} />Back to inventory</Link><div className="detail-hero"><div className="food-initial food-initial--large">{item.food.name.charAt(0)}</div><div><p className="eyebrow">{item.food.category}</p><h1>{item.food.name}</h1><p className="detail-quantity">{Number(item.quantity_remaining).toLocaleString()} {item.unit} remaining</p></div><StatusBadge status={status} /></div>
    <div className="detail-layout"><div className="detail-main">{prediction && <section className="risk-panel"><div className="risk-panel__score"><p className="eyebrow">Waste Risk Score</p><RiskBadge prediction={prediction} /><small>Explainable application estimate</small></div><div className="risk-panel__explanation"><h2>Why {riskLabel(prediction.risk_level).toLowerCase()}?</h2><ul>{prediction.explanation.slice(0, 4).map((reason) => <li key={reason}>{reason}</li>)}</ul><div className="recommendation"><strong>Recommended action</strong><span>{prediction.recommendation}</span></div></div></section>}
    {prediction && <section id="rescue" className="ai-rescue-panel"><div className="ai-rescue-panel__intro"><span><Sparkles /></span><div><p className="eyebrow">AI food rescue</p><h2>Turn risk into a meal.</h2><p>Gemini can suggest practical recipes using this food and what you already have. It never changes the deterministic risk score.</p></div><button className="button ai-button" disabled={aiLoading || days < 0} onClick={generate}><Sparkles size={16} />{recipes.length ? 'Generate fresh options' : 'Find rescue recipes'}</button></div>{days < 0 && <div className="notice notice--warning">This item is past its estimated expiry, so ShelfSense will not recommend consuming it.</div>}{aiLoading && <AIGenerationState />}{aiError && <div className="notice notice--error">{aiError}<button className="text-button" onClick={generate}>Try again</button></div>}{!aiLoading && recipes.length > 0 && <><div className="ai-insight"><strong>ShelfSense insight</strong><p>{recipes[0].ai_insight}</p></div><div className="recipe-options">{recipes.map((recipe) => <RecipeCard key={recipe.id} recipe={recipe} />)}</div></>}</section>}
    <div className="detail-grid"><Fact icon={ShoppingBasket} label="Purchased" value={formatDate(item.purchase_date)} /><Fact icon={CalendarDays} label="Estimated expiry" value={formatDate(expiry)} hint={days == null ? 'Shelf life unavailable' : days < 0 ? `${Math.abs(days)} days past estimate` : `${days} days remaining`} /><Fact icon={MapPin} label="Storage" value={formatStorage(item.storage_type)} /><Fact icon={Package} label="Purchase price" value={formatMoney(item.purchase_price)} /></div>{item.notes && <div className="notes-block"><p className="eyebrow">Notes</p><p>{item.notes}</p></div>}</div><aside className="action-panel"><h2>Update this item</h2><p>Record what happened so your inventory stays accurate.</p><button className="button button--wide" disabled={item.status !== 'active'} onClick={() => setModal('consume')}>Consume food</button><button className="button button--secondary button--wide" disabled={item.status !== 'active'} onClick={() => setModal('waste')}>Mark as waste</button><button className="button button--ghost button--wide" onClick={() => setModal('edit')}><Edit3 size={16} />Edit details</button><button className="danger-button" onClick={() => setModal('delete')}><Trash2 size={15} />Delete item</button></aside></div>
    {modal === 'consume' && <QuantityModal type="consume" item={item} onClose={() => setModal(null)} onComplete={completeAction} />}
    {modal === 'waste' && <QuantityModal type="waste" item={item} onClose={() => setModal(null)} onComplete={completeAction} />}
    {modal === 'edit' && <Modal title="Edit inventory item" description="Historical consumption and waste records are not changed." onClose={() => setModal(null)}><InventoryForm foods={[item.food]} initialValues={{ ...item, quantity_purchased: String(item.quantity_purchased), quantity_remaining: String(item.quantity_remaining), purchase_price: item.purchase_price ?? '', custom_expiry_date: item.custom_expiry_date ?? '', notes: item.notes ?? '' }} submitLabel="Save changes" onSubmit={async (values) => { const { error: updateError } = await updateInventoryItem(item.id, values); if (updateError) throw updateError; setModal(null); await load(true) }} /></Modal>}
    {modal === 'delete' && <Modal title="Delete this inventory item?" description="This permanently removes the item and its linked consumption, waste, prediction, and notification history." onClose={() => setModal(null)}><div className="modal-actions"><button className="button button--ghost" onClick={() => setModal(null)}>Cancel</button><button className="button button--danger" onClick={async () => { const { error: deleteError } = await deleteInventoryItem(item.id); if (deleteError) return console.error('Delete failed', deleteError); navigate('/inventory') }}>Delete permanently</button></div></Modal>}
  </section>
}

function Fact({ icon: Icon, label, value, hint }) { return <div className="detail-fact"><span><Icon size={18} /></span><div><small>{label}</small><strong>{value}</strong>{hint && <em>{hint}</em>}</div></div> }

function QuantityModal({ type, item, onClose, onComplete }) {
  const [quantity, setQuantity] = useState(''); const [reason, setReason] = useState('Spoiled'); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const label = type === 'consume' ? 'Consume food' : 'Record food waste'
  const submit = async (event) => { event.preventDefault(); const amount = Number(quantity); if (!(amount > 0)) return setError('Enter a quantity greater than zero.'); if (amount > Number(item.quantity_remaining)) return setError(`You only have ${Number(item.quantity_remaining).toLocaleString()} ${item.unit} remaining.`); setBusy(true); try { await onComplete(type, { quantity: amount, reason, notes }) } catch (actionError) { console.error(`${type} action failed`, actionError); setError('We couldn’t save this update. Please try again.'); setBusy(false) } }
  return <Modal title={label} description={`Current quantity: ${Number(item.quantity_remaining).toLocaleString()} ${item.unit}`} onClose={onClose}><form className="modal-form" onSubmit={submit}><div className="field"><label htmlFor="action-quantity">Quantity ({item.unit})</label><input id="action-quantity" autoFocus type="number" min="0.001" max={item.quantity_remaining} step="0.001" value={quantity} onChange={(e) => { setQuantity(e.target.value); setError('') }} /></div>{type === 'waste' && <div className="field"><label htmlFor="waste-reason">Reason</label><select id="waste-reason" value={reason} onChange={(e) => setReason(e.target.value)}>{['Spoiled', 'Expired', 'Over-purchased', 'Taste/quality', 'Other'].map((entry) => <option key={entry}>{entry}</option>)}</select></div>}<div className="field"><label htmlFor="action-notes">Notes <span>Optional</span></label><textarea id="action-notes" rows="2" value={notes} onChange={(e) => setNotes(e.target.value)} /></div>{error && <div className="notice notice--error">{error}</div>}<div className="modal-actions"><button type="button" className="button button--ghost" onClick={onClose}>Cancel</button><button className="button" disabled={busy}>{busy ? 'Saving…' : label}</button></div></form></Modal>
}
